#pragma once
#include <vector>
#include "Character.h"

std::vector<Character> Characters
{
	Character("Mario", "Mario", "Mro"),
	Character("Luigi", "Luigi", "Lig"),
	Character("Peach", "Peach", "Pch"),
	Character("Daisy", "Daisy", "Dsy"),
	Character("Yoshi", "Yoshi00", "Ysi0"),
	Character("Red Yoshi", "Yoshi01", "Ysi1"),
	Character("Blue Yoshi", "Yoshi02", "Ysi2"),
	Character("Light Blue Yoshi", "Yoshi03", "Ysi3"),
	Character("Yellow Yoshi", "Yoshi04", "Ysi4"),
	Character("Pink Yoshi", "Yoshi05", "Ysi5"),
	Character("Black Yoshi", "Yoshi06", "Ysi6"),
	Character("White Yoshi", "Yoshi07", "Ysi7"),
	Character("Orange Yoshi", "Yoshi08", "Ysi8"),
	Character("Toad", "Kinopio", "Kno"),
	Character("Koopa Troopa", "Nokonoko", "Nok"),
	Character("Shy Guy", "Heyho00", "Hyh0"),
	Character("Green Shy Guy", "Heyho01", "Hyh1"),
	Character("Blue Shy Guy", "Heyho02", "Hyh2"),
	Character("Light Blue Shy Guy", "Heyho03", "Hyh3"),
	Character("Yellow Shy Guy", "Heyho04", "Hyh4"),
	Character("Pink Shy Guy", "Heyho05", "Hyh5"),
	Character("Black Shy Guy", "Heyho06", "Hyh6"),
	Character("White Shy Guy", "Heyho07", "Hyh7"),
	Character("Orange Shy Guy", "Heyho08", "Hyh8"),
	Character("Baby Mario", "BbMario", "MroB"),
	Character("Baby Luigi", "BbLuigi", "LgiB"),
	Character("Baby Peach", "BbPeach", "PchB"),
	Character("Baby Daisy", "BbDaisy", "DsyB"),
	Character("Bowser", "Koopa", "Kop"),
	Character("Donkey Kong", "DK", "Dkg"),
	Character("Wario", "Wario", "Wro"),
	Character("Waluigi", "Waluigi", "Wlg"),
	Character("Rosalina", "Rosetta", "Rst"),
	Character("Metal Mario", "MetalMario", "MroM"),
	Character("Gold Mario", "GoldMario", "MroM"),
	Character("Lakitu", "Jugemu", "Jgm"),
	Character("Toadette", "Kinopico", "Knc"),
	Character("Baby Rosalina", "BbRosetta", "RstB"),
	Character("Pink Gold Peach", "PGoldPeach", "PchG"),
	Character("Iggy", "Iggy", "Igy"),
	Character("Roy", "Roy", "Roy"),
	Character("Lemmy", "Lemmy", "Lmy"),
	Character("Larry", "Larry", "Lry"),
	Character("Wendy", "Wendy", "Wdy"),
	Character("Ludwig", "Ludwig", "Ldw"),
	Character("Morton", "Morton", "Mtn"),
	Character("Mii", "Mii", "Mii0"),
	Character("Tanooki Mario", "TanukiMario", "MroT"),
	Character("Cat Peach", "CatPeach", "PchN"),
	Character("Link", "Link", "Lnk"),
	Character("BOTW-Link", "LinkBotw", "LnkB"),
	Character("Villager Boy", "AnimalBoyA", "BoyA"),
	Character("Villager Girl", "AnimalGirlA", "Mrg"),
	Character("Isabelle", "Shizue", "Sze"),
	Character("Dry Bowser", "HoneKoopa", "KopH"),
	Character("King Boo", "KingTeresa", "Ktr"),
	Character("Dry Bones", "Karon", "Krn"),
	Character("Bowser Jr.", "KoopaJr", "KopJ"),
	Character("Inkling Girl", "SplatoonGirl00", "SplG0"),
	Character("Green Inkling Girl", "SplatoonGirl01", "SplG1"),
	Character("Pink Inkling Girl", "SplatoonGirl02", "SplG2"),
	Character("Inkling Boy", "SplatoonBoy00", "SplB0"),
	Character("Purple Inkling Boy", "SplatoonBoy01", "SplB1"),
	Character("Light Blue Inkling Boy", "SplatoonBoy02", "SplB2")
};