#pragma once
#include <vector>
#include "KartPart.h"

std::vector<KartPart> KartParts
{
	// Karts
	KartPart("Standard Kart", "tc_KP_K_Std"),
	KartPart("Pipe Frame", "tc_KP_K_Skl"),
	KartPart("Mach 8", "tc_KP_K_Ufo"),
	KartPart("Steel Driver", "tc_KP_K_Sbm"),
	KartPart("Cat Cruiser", "tc_KP_K_Cat"),
	KartPart("Circuit Special", "tc_KP_K_Fml"),
	KartPart("Tri-Speeder", "tc_KP_K_Tri"),
	KartPart("Badwagon", "tc_KP_K_Wld"),
	KartPart("Prancer", "tc_KP_K_Pch"),
	KartPart("Buggybud", "tc_KP_K_Ten"),
	KartPart("Landship", "tc_KP_K_Shp"),
	KartPart("Bounder", "tc_KP_K_Snk"),
	KartPart("Sports Coupe", "tc_KP_K_Spo"),
	KartPart("Gold Kart", "tc_KP_K_Gld"),
	KartPart("GLA", "tc_KP_K_Gla"),
	KartPart("W 25 Silver Arrow", "tc_KP_K_Slv"),
	KartPart("300 SL Roadster", "tc_KP_K_Rst"),
	KartPart("Blue Falcon", "tc_KP_K_Bfl"),
	KartPart("Tanooki Kart", "tc_KP_K_Tnk"),
	KartPart("B Dasher", "tc_KP_K_Bds"),
	KartPart("Streetle", "tc_KP_K_Btl"),
	KartPart("P-Wing", "tc_KP_K_Pwc"),
	KartPart("Koopa Clown", "tc_KP_K_Kpc"),
	// Bikes
	KartPart("Standard Bike", "tc_KP_B_Std"),
	KartPart("The Duke", "tc_KP_B_Big"),
	KartPart("Flame Rider", "tc_KP_B_Amb"),
	KartPart("Varmint", "tc_KP_B_Mix"),
	KartPart("Mr Scooty", "tc_KP_B_Kid"),
	KartPart("City Tripper", "tc_KP_B_Sct"),
	KartPart("Master Cycle Zero", "tc_KP_B_Bow"),
	KartPart("Comet", "tc_KP_B_Fro"),
	KartPart("Sport Bike", "tc_KP_B_Mgp"),
	KartPart("Jet Bike", "tc_KP_B_Jet"),
	KartPart("Yoshi Bike", "tc_KP_B_Ysi"),
	KartPart("Master Cycle", "tc_KP_B_Zld"),
	// ATVs
	KartPart("Standard Quad", "tc_KP_V_Atv"),
	KartPart("Wild Wiggler", "tc_KP_V_Hnc"),
	KartPart("Teddy Buggy", "tc_KP_V_Bea"),
	KartPart("Bone Rattler", "tc_KP_V_Drb"),
	KartPart("Splat Buggy", "tc_KP_V_Spl"),
	KartPart("Inkstriker", "tc_KP_V_Tnd"),
	// Tyres
	KartPart("Normal", "tc_KP_T_Std"),
	KartPart("Monster", "tc_KP_T_Big"),
	KartPart("Roller", "tc_KP_T_Sml"),
	KartPart("Slim", "tc_KP_T_Rng"),
	KartPart("Slick", "tc_KP_T_Slk"),
	KartPart("Metal", "tc_KP_T_Mtl"),
	KartPart("Button", "tc_KP_T_Btn"),
	KartPart("Off-Road", "tc_KP_T_Ofr"),
	KartPart("Sponge", "tc_KP_T_Spg"),
	KartPart("Wooden", "tc_KP_T_Wod"),
	KartPart("Cushion", "tc_KP_T_Fun"),
	KartPart("Normal Blue", "tc_KP_T_Zst"),
	KartPart("Funky Monster", "tc_KP_T_Zbi"),
	KartPart("Azure Roller", "tc_KP_T_Zsm"),
	KartPart("Crimson Slim", "tc_KP_T_Zrn"),
	KartPart("Cyber Slick", "tc_KP_T_Zsl"),
	KartPart("Retro Off-Road", "tc_KP_T_Zof"),
	KartPart("Gold Wheels", "tc_KP_T_Gld"),
	KartPart("GLA Wheels", "tc_KP_T_Gla"),
	KartPart("Triforce Tyres", "tc_KP_T_Tri"),
	KartPart("Leaf Tyres", "tc_KP_T_Anm"),
	KartPart("Ancient Tyres", "tc_KP_T_Bow"),
	// Gliders
	KartPart("Super Glider", "tc_KP_G_Std"),
	KartPart("Cloud Glider", "tc_KP_G_Jgm"),
	KartPart("Wario Wing", "tc_KP_G_Wlo"),
	KartPart("Waddle Wing", "tc_KP_G_Zng"),
	KartPart("Peach Parasol", "tc_KP_G_Umb"),
	KartPart("Parachute", "tc_KP_G_Prc"),
	KartPart("Parafoil", "tc_KP_G_Prf"),
	KartPart("Flower Glider", "tc_KP_G_Flw"),
	KartPart("Bowser Kite", "tc_KP_G_Kpa"),
	KartPart("Plane Glider", "tc_KP_G_Spl"),
	KartPart("MKTV Parafoil", "tc_KP_G_Ptv"),
	KartPart("Gold Glider", "tc_KP_G_Gld"),
	KartPart("Hylian Kite", "tc_KP_G_Hyr"),
	KartPart("Paper Glider", "tc_KP_G_Pap"),
	KartPart("Paraglider", "tc_KP_G_Bow")
};